version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python bookmarks/manage.py migrate && python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./bookmarks:/app
    ports:
      - 8000:8000

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  stripe:
    image: stripe/stripe-cli:v1.17.2
    command:
      [
        "listen",
        "--forward-to",
        "localhost:80000/payment/webhook/",
        "--api-keys",
        "${STRIPE_SECRET_KEY}",
      ]
    networks:
      - web
    depends_on:
      - web

  redis:
    image: redis
    ports:
      - "6379:6379"
